### ISSUE TITLE
Bug after launch

### ISSUE THREAD

**Issue by shatk0vskiy** [softhausHQ/CircleBar#10]
Video: https://youtu.be/7pJKqMV4nb0

**Comment by bhdrbkc** [comment]
no solution?

**Comment by herrkayser** [comment]
got the same issue.

**Comment by herrkayser** [comment]
The problem seems to be the fixed y-position of the `circleView.frame` in the `viewDidLoad()` method of the `SHCircleBarController`. It is set to `self.tabBar.frame.origin.y - 40` which looks different for the different screen sizes.

**Comment by herrkayser** [comment]
it seems to be the result of the bottom safe are height on newer devices (X,XS,XR,...)

**Comment by bhdrbkc** [comment]
great,
thank you for your help
