### ISSUE TITLE
Change IconTintColor

### ISSUE THREAD

**Issue by Timonator1606** [softhausHQ/CircleBar#20]
Is it possible to change the TintColor of the unselected Tabbar Icons?
The only thing I get worked is to change the background colors and the color of the selected Icon.

**Comment by Luccifer** [comment]
Same here

**Comment by carlos0193** [comment]
> Is it possible to change the TintColor of the unselected Tabbar Icons?
> The only thing I get worked is to change the background colors and the color of the selected Icon.

set UIColor.white.set() or the color that you want


 private func image(with image: UIImage?, scaledTo newSize: CGSize) -> UIImage? {
        image?.withRenderingMode(.alwaysTemplate)
        UIGraphicsBeginImageContextWithOptions(newSize, _: false, _: 0.0)
        UIColor.white.set()
        image?.draw(in: CGRect(x: 0, y: 0, width: newSize.width, height: newSize.height))
        let newImage: UIImage? = UIGraphicsGetImageFromCurrentImageContext()
       
        UIGraphicsEndImageContext()
        
        return newImage
    }

**Comment by carlos0193** [comment]
> Is it possible to change the TintColor of the unselected Tabbar Icons?
> The only thing I get worked is to change the background colors and the color of the selected Icon.

You need to change the class with this

        image?.withRenderingMode(.alwaysTemplate)
set UIColor.white.set() or the color that you want

` private func image(with image: UIImage?, scaledTo newSize: CGSize) -> UIImage? {
        image?.withRenderingMode(.alwaysTemplate)
        UIGraphicsBeginImageContextWithOptions(newSize, _: false, _: 0.0)
        UIColor.white.set()
        image?.draw(in: CGRect(x: 0, y: 0, width: newSize.width, height: newSize.height))
        let newImage: UIImage? = UIGraphicsGetImageFromCurrentImageContext()
       
        UIGraphicsEndImageContext()
        
        return newImage
    }`

**Comment by carlos0193** [comment]
You need to change the class with this

        image?.withRenderingMode(.alwaysTemplate)
set UIColor.white.set() or the color that you want

` private func image(with image: UIImage?, scaledTo newSize: CGSize) -> UIImage? {
        image?.withRenderingMode(.alwaysTemplate)
        UIGraphicsBeginImageContextWithOptions(newSize, _: false, _: 0.0)
        UIColor.white.set()
        image?.draw(in: CGRect(x: 0, y: 0, width: newSize.width, height: newSize.height))
        let newImage: UIImage? = UIGraphicsGetImageFromCurrentImageContext()
       
        UIGraphicsEndImageContext()
        
        return newImage
    }`

**Comment by carlos0193** [comment]
You need to change the class with this

        image?.withRenderingMode(.alwaysTemplate)
        UIColor.white.set() 
or the color that you want

        private func image(with image: UIImage?, scaledTo newSize: CGSize) -> UIImage? {
        image?.withRenderingMode(.alwaysTemplate)
        UIGraphicsBeginImageContextWithOptions(newSize, _: false, _: 0.0)
        UIColor.white.set()
        image?.draw(in: CGRect(x: 0, y: 0, width: newSize.width, height: newSize.height))
        let newImage: UIImage? = UIGraphicsGetImageFromCurrentImageContext()
       
        UIGraphicsEndImageContext()
        
        return newImage
        }

**Comment by Timonator1606** [comment]
Thx Carlos, but this is not working. As you can see in the pics the color is still the same. In the one pic I tried color "red" and in the other one "white". It's still the same dark gray. 

![IMG_0943](https://user-images.githubusercontent.com/68296076/105842327-475f4c80-5fd6-11eb-9035-8b8eec03bfb3.jpeg)
![IMG_0942](https://user-images.githubusercontent.com/68296076/105842331-48907980-5fd6-11eb-867d-1a72dde2d031.jpeg)

**Comment by Timonator1606** [comment]
Guys, I got it. 

Just put this: 

`tabBar.unselectedItemTintColor = .white`

directly under: 

`tabBar.select(itemAt: index, animated: true)`

in the first `open override var selectedViewController: UIViewController? { ...` in SHCircleBarController.swift in the Pods file. 


The beginning of SHCircleBarController.swift should look like this:

`fileprivate var shouldSelectOnTabBar = true
    private var circleView : UIView!
    private var circleImageView: UIImageView!
    open override var selectedViewController: UIViewController? {
        willSet {
            guard shouldSelectOnTabBar, let newValue = newValue else {
                shouldSelectOnTabBar = true
                return
            }
 
            guard let tabBar = tabBar as? SHCircleBar, let index = viewControllers?.firstIndex(of: newValue) else {return}
 
            tabBar.select(itemAt: index, animated: true)
            tabBar.unselectedItemTintColor = .white
        }`

Have a nice day.

**Comment by carlos0193** [comment]
> Thx Carlos, but this is not working. As you can see in the pics the color is still the same. In the one pic I tried color "red" and in the other one "white". It's still the same dark gray.
> 
> ![IMG_0943](https://user-images.githubusercontent.com/68296076/105842327-475f4c80-5fd6-11eb-9035-8b8eec03bfb3.jpeg)
> ![IMG_0942](https://user-images.githubusercontent.com/68296076/105842331-48907980-5fd6-11eb-867d-1a72dde2d031.jpeg)

to change the color of the image you need
       
        image?.withRenderingMode(.alwaysTemplate)

or en assets on selected images you can change Render As: template image

<img width="267" alt="Screen Shot 2021-01-26 at 7 51 12" src="https://user-images.githubusercontent.com/33667509/105868690-4bc24000-5fab-11eb-9c1a-73c0f00c7070.png">

**Comment by carlos0193** [comment]
And try this to unselect Item

> Chicos, lo tengo.
> 
> Solo pon esto:
> 
> `tabBar.unselectedItemTintColor = .white`
> 
> directamente debajo de:
> 
> `tabBar.select(itemAt: index, animated: true)`
> 
> en el primero `open override var selectedViewController: UIViewController? { ...`en SHCircleBarController.swift en el archivo Pods.
> 
> El comienzo de SHCircleBarController.swift debería verse así:
> 
> `fileprivate var shouldSelectOnTabBar = true
> private var circleView: UIView!
> private var circleImageView: UIImageView!
> abrir override var selectedViewController: UIViewController? {
> willSet {
> guard shouldSelectOnTabBar, let newValue = newValue else {
> shouldSelectOnTabBar = true
> return
> }
> 
> ```
>         guard let tabBar = tabBar as? SHCircleBar, let index = viewControllers?.firstIndex(of: newValue) else {return}
> 
>         tabBar.select(itemAt: index, animated: true)
>         tabBar.unselectedItemTintColor = .white
>     }`
> ```
> 
> Que tengas un buen día.
