### ISSUE TITLE
tab bar item is not hide when hides the whole tab bar

### ISSUE THREAD

**Issue by khaledbohout2** [softhausHQ/CircleBar#22]
**Describe the bug**
tab bar item is not disappearing when hides the whole tab bar

**To Reproduce**
1. hide the tab bar in any view controller it hides but item stays

**Expected behavior**
the tab bar item also disappear with the whole tab bar

**Comment by carlos0193** [comment]
did you find the solution?

> **Describa que el**
> elemento de la barra de pestañas de **errores** no desaparece cuando oculta toda la barra de pestañas
> 
> **Para reproducir**
> Pasos para reproducir el comportamiento:
> 
> 1. ocultar la barra de pestañas en cualquier controlador de vista que oculta pero el elemento permanece
> 
> **Comportamiento esperado**
> el elemento de la barra de pestañas también desaparece con toda la barra de pestañas

**Comment by Timonator1606** [comment]
I did it with an NSNotification in to the SHCircleBarController.swift.

Put this in the Code when the Tabbar should hide. For example in an UIViewController:

`NotificationCenter.default.post(name: NSNotification.Name(rawValue: "deactivateTab"), object: .none)
  self.tabBarController?.tabBar.isHidden = true`

Then, put the following into the "viewDidLoad" in the SHCircleBarController.swift in the PodFiles:

`NotificationCenter.default.addObserver(self, selector: #selector(deactivateTab), name: NSNotification.Name(rawValue: "deactivateTab"), object: .none)`

At the end, put the following Function into the same SHCircleBarController.swift in the PodFiles where ever you want:

`@objc func deactivateTab() {
        circleView.isHidden = true
    }`

This will hide the whole Tabbar. 


The bring it back, do the following: 

Put this in the Code when the Tabbar should be visible. For example in an UIViewController:

`NotificationCenter.default.post(name: NSNotification.Name(rawValue: "activateTab"), object: .none)
  self.tabBarController?.tabBar.isHidden = false`

Then, put the following into the "viewDidLoad" in the SHCircleBarController.swift in the PodFiles:

`NotificationCenter.default.addObserver(self, selector: #selector(activateTab), name: NSNotification.Name(rawValue: "activateTab"), object: .none)`

At the end, put the following Function into the same SHCircleBarController.swift in the PodFiles where ever you want:

`@objc func activateTab() {
        circleView.isHidden = false
    }`

This will show the whole Tabbar again.

**Comment by carlos0193** [comment]
> `@objc func activateTab() { circleView.isHidden = false }`

Thanks bro, its working!!!
you save me

**Comment by carlos0193** [comment]
> Lo hice con una NSNotification en SHCircleBarController.swift.
> 
> Pon esto en el código cuando la barra de pestañas debería ocultarse. Por ejemplo, en un UIViewController:
> 
> `NotificationCenter.default.post(name: NSNotification.Name(rawValue: "deactivateTab"), object: .none) self.tabBarController?.tabBar.isHidden = true`
> 
> Luego, coloque lo siguiente en "viewDidLoad" en SHCircleBarController.swift en PodFiles:
> 
> `NotificationCenter.default.addObserver(self, selector: #selector(deactivateTab), name: NSNotification.Name(rawValue: "deactivateTab"), object: .none)`
> 
> Al final, coloque la siguiente función en el mismo SHCircleBarController.swift en los PodFiles donde quiera:
> 
> `@objc func deactivateTab() { circleView.isHidden = true }`
> 
> Esto ocultará toda la barra de pestañas.
> 
> Para traerlo de vuelta, haz lo siguiente:
> 
> Pon esto en el código cuando la barra de pestañas debería estar visible. Por ejemplo, en un UIViewController:
> 
> `NotificationCenter.default.post(name: NSNotification.Name(rawValue: "activateTab"), object: .none) self.tabBarController?.tabBar.isHidden = false`
> 
> Luego, coloque lo siguiente en "viewDidLoad" en SHCircleBarController.swift en PodFiles:
> 
> `NotificationCenter.default.addObserver(self, selector: #selector(activateTab), name: NSNotification.Name(rawValue: "activateTab"), object: .none)`
> 
> Al final, coloque la siguiente función en el mismo SHCircleBarController.swift en los PodFiles donde quiera:
> 
> `@objc func activateTab() { circleView.isHidden = false }`
> 
> Esto mostrará toda la barra de pestañas nuevamente.

thanks bro, its working!
you save me
