### ISSUE TITLE
SHCircleBar vs 

### ISSUE THREAD

**Issue by joshwolff1** [softhausHQ/CircleBar#4]
Correct me if I'm wrong, but the README says:

> Set the class of the UITabBarController to SHTabBarController in your Storyboard or nib.
> Set the class of the UITabBar of SHTabBarController to SHTabBar in your Storyboard or nib.

Shouldn't it be?
> Set the class of the UITabBarController to SHCircleBarController in your Storyboard or nib.
> Set the class of the UITabBar of SHCircleBarController to SHCircleBar in your Storyboard or nib.

The latter worked for me, the former did not, and in fact it just finished building onto my iPhone and it looks awesome! Nice work!

**Comment by perteadrian** [comment]
@joshwolff1 ,  thanks for observing the mistake 
now it is fixed.
