### ISSUE TITLE
View gets stuck

### ISSUE THREAD

**Issue by joshwolff1** [softhausHQ/CircleBar#5]
**Describe the bug**
The view gets stuck on the app icon if I segue to any other UINavigationViewController then use an unwind segue to get back.

**To Reproduce**
1. Load into the CircleBarController.
2. Segue to a UINavigationViewController.
3. Unwind back. 
4. Switch tabs.

See the behavior / bug here:
https://youtu.be/pMLhlNLp9pI
See how it is caused here: (Note I segue to the Messages tabbarview controller)
https://youtu.be/W9nSDG_fVLk

**Comment by joshwolff1** [comment]
Basically, it works. Then you segue. Then you unwind. And it gets stuck

**Comment by joshwolff1** [comment]
Clearer video of how it is caused here: https://youtu.be/jdwUzHPFNbQ

**Comment by perteadrian** [comment]
Hello @joshwolff1, thanks for reporting this. 
I will do an update as soon as possible.

**Comment by perteadrian** [comment]
@joshwolff1 , I updated the library

**Comment by joshwolff1** [comment]
Thank you!
