### ISSUE TITLE
Error while installing using Pod

### ISSUE THREAD

**Issue by lekhakmukesh** [softhausHQ/CircleBar#9]
Unable to install pod. 

1. Add "  pod 'CircleBar'  "
2. Pod install 
3. Error " [!] Unable to find a specification for `CircleBar` "

Need help

**Comment by perfaram** [comment]
Can confirm (Cocoapods 1.6.1, Xcode 10.1, targeting iOS 12.0, with modules activated and `use_frameworks!` in the Podfile)

**Comment by perfaram** [comment]
See #3 for a possible workaround (no time to check, I just directly included the files without use the Pod)
